<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="C:\Users\faiez\.nuget\packages\microsoft.visualstudio.diagnosticshub.benchmarkdotnetdiagnosers\18.3.36812.1\contentFiles\cs\any\BenchmarkProfilerAgentConfig.g.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.10" />
    <PackageReference Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" Version="18.3.36812.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AssetFlowCore.Application\AssetFlowCore.Application.csproj" />
    <ProjectReference Include="..\AssetFlowCore.Domain\AssetFlowCore.Domain.csproj" />
    <ProjectReference Include="..\AssetFlowCore.Infrastructure\AssetFlowCore.Infrastructure.csproj" />
  </ItemGroup>
</Project>
