<Project Sdk="Aspire.AppHost.Sdk/13.4.5">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>c000a2b3-7201-4c36-a243-ec3c7a79fa0e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.4.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AssetFlowCore.WebApi\AssetFlowCore.WebApi.csproj" />
  </ItemGroup>

</Project>
