<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<PreserveCompilationContext>true</PreserveCompilationContext>
	<UserSecretsId>0a7f6a57-a42e-4709-b056-9cd46869086f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" Version="13.4.5" />
	<PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AssetFlowCore.Application\AssetFlowCore.Application.csproj" />
    <ProjectReference Include="..\AssetFlowCore.Aspire\AssetFlowCore.Aspire.ServiceDefaults\AssetFlowCore.Aspire.ServiceDefaults.csproj" />
    <ProjectReference Include="..\AssetFlowCore.Infrastructure\AssetFlowCore.Infrastructure.csproj" />
  </ItemGroup>

</Project>
