<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" Version="13.4.6" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageReference Include="TngTech.ArchUnitNET" Version="0.13.3" />
	  <PackageReference Include="TngTech.ArchUnitNET.xUnit" Version="0.13.3" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AssetFlowCore.Application\AssetFlowCore.Application.csproj" />
    <ProjectReference Include="..\AssetFlowCore.Aspire\AssetFlowCore.Aspire.AppHost\AssetFlowCore.Aspire.AppHost.csproj" />
    <ProjectReference Include="..\AssetFlowCore.Domain\AssetFlowCore.Domain.csproj" />
    <ProjectReference Include="..\AssetFlowCore.Infrastructure\AssetFlowCore.Infrastructure.csproj" />
    <ProjectReference Include="..\AssetFlowCore.WebApi\AssetFlowCore.WebApi.csproj" />
  </ItemGroup>

</Project>
